package si.um.feri.maprri.models.enums;

public enum WorkerType {
    MINER,
    MACHINEOPERATOR,
    BLASTINGTECHNICIAN,
    MAINTENANCEWORKER,
    SURVEYOR, // GEODET
    GEOLOGIST,
    MININGENGINEER,
    SAFETYTECHNICIAN,
    VENTILATIONENGINEER,
    HYDROLOGIST,
    ELECTRICTIAN,
    SUPERVISOR,
    LABORATORYTECHNICIAN,
    DIRECTOR,
    PRODUCTIONMANAGER,
    HUMANRESOURCES,
    ACCOUNTANT,
    UNDEFINED
}
